### PR TITLE
Configure coredns to point some anduin.local domains to minikube's node IP

### PR DESCRIPTION
**Pull request by ubolonton**
To help with Ingress.

### CODE REVIEW

**Comment by keimoon** [comment]
This is public repo so we should not expose our internal domain here. I will push a PR to your branch in gondor to change the necessary domain to svc.kube

**Comment by ubolonton** [comment]
Reusing `svc.kube` is not a clean solution. It would still be preferable to use a custom zone.

However, I agree that putting these domain names here is not desirable, since it makes the tool less generic (not because of security).

I think the better approach would be:
- Make `anduin-kube` support custom zone file.
- Add initialization script to the specific repository that adds root cert and provides `anduin-kube` the necessary zone file.

Thoughts?

**Comment by keimoon** [comment]
Yeah, I also think this is better approach.

**Comment by ngbinh** [comment]
so, should we close this?

**Pull request closed without merging**
